import React from 'react';

export const metadata = {
  title: 'profile Next App',
  description: 'Generated by create next app',
}

const profile = () => {
  return (
    <div>
      profile
    </div>
  );
};

export default profile;