import Link from 'next/link';
import React from 'react';

export const metadata = {
  title: 'blogs | Next App',
  description: 'Generated by create next app',
}


const blogs = [
  {
    id: 1, 
    year: 2016,
    title: 'title 1'
  },
  {
    id: 2, 
    year: 2016,
    title: 'title 2'
  },
  {
    id: 3, 
    year: 2016,
    title: 'title 3'
  },
  {
    id: 4, 
    year: 2016,
    title: 'title 4'
  },
]

const blogPage = () => {
  
  return (
    <div className='container mx-auto'>
      {

        //this is normal router


        // blogs.map(({id, year , title}) => <Link className='block border-blue-500 p-5 border-2 m-2' href={`/blogs/${year}/${id}`} key={id}>{title}</Link>)



        //this is queary router

        
        blogs.map(({id, year , title}) => <Link  className={`block border-blue-500 p-5 border-2 m-2 `}
        href={
          {
            pathname: `/blogs/${year}/${id}`,
            query: {
              title: title,
            }
          }
        } key={id}>{title}</Link>)

        


      }
    </div>
  );
};

export default blogPage;