import React from 'react';
export const metadata = {
  title: 'Add-Product | Dashboard Next App',
  description: 'Generated by create next app',
}

const add_product = () => {
  return (
    <div>
      product
    </div>
  );
};

export default add_product;