import React from 'react';
import Sidebar from './Sidebar';

export const metadata = {
  title: 'Dashboard Next App',
  description: 'Generated by create next app',
}

const dashboardLayout = ({children}) => {
  return (
    <div className='flex container mx-auto'>
      <Sidebar></Sidebar>
      {children}
    </div>
  );
};

export default dashboardLayout;